// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spravce_hesel.Data;

#nullable disable

namespace Spravce_hesel.Migrations
{
    [DbContext(typeof(Spravce_heselData))]
    [Migration("20221030184927_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Spravce_hesel.Models.Heslo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Hash")
                        .HasColumnType("int");

                    b.Property<string>("Jmeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Sifra")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Sluzba")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzivatelskeID")
                        .HasColumnType("int");

                    b.Property<string>("desifrovano")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hesla");
                });

            modelBuilder.Entity("Spravce_hesel.Models.SdileneHeslo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Jmeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Potvrzeno")
                        .HasColumnType("bit");

                    b.Property<int>("PuvodniHesloID")
                        .HasColumnType("int");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sluzba")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzivatelskeID")
                        .HasColumnType("int");

                    b.Property<int>("ZakladatelID")
                        .HasColumnType("int");

                    b.Property<string>("ZakladatelJmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sdilena_hesla");
                });

            modelBuilder.Entity("Spravce_hesel.Models.Uzivatel", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Heslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("IV")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("Uzivatele");
                });
#pragma warning restore 612, 618
        }
    }
}
